eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true

  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

server:
  port: 8081