spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: route
          uri: lb://client-service
          predicates:
            - Path=/api/client/
            - Method=GET

server:
  port: 8090