eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books

server:
  port: 8086
