spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    log-delta-diff: false
    eureka-server-connect-timeout-seconds: 60